name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check HTML
        run: echo "HTML OK"

      - name: Check CSS
        run: echo "CSS OK"

      - name: Check JS
        run: echo "JS OK"